### ISSUE TITLE
Issues with latest master

### ISSUE THREAD

**Issue by jancborchardt** [postapczuk/Light-Android-Launcher#23]
@postapczuk the latest commits introduced some bugs:

- [x] AllAppsActivity uses 100 padding instead of using the same padding values as on the MainActivity (favorites view). As I mentioend at https://github.com/postapczuk/Light-Android-Launcher/pull/22#issuecomment-443496846:
  > I  only needed to hand the padding from `getTotalHeightofListView` we get in MainActivity over to the AllAppsActivity.
  > A better method to do that would be great. The values themselves (centering the favorites vertically, and using 1/6 of screen size for left padding) seem great though. :)
- [x] Now a second bug appeared (via 0748077d2610482fc731848e852e716028e163eb or 68b46523c8ffa5b0b74b188242a41fb4e714d35f) which leads to the All apps list starting in the middle, and it being impossible to scroll up.
- [x] The "+ add application" should probably be called "+ Add favorite app" to make it more clear. Is it also possible to make the text grey so it’s less distracting?

-----------------------

In other projects with more contributors we generally do all changes via pull requests, with required reviews from the others. Then we can catch issues like these directly during review. :)

**Comment by postapczuk** [comment]
two first bugs were fixed

**Comment by postapczuk** [comment]
I would name the third one as a feature ;)

**Comment by jancborchardt** [comment]
The first bug was not fixed though? :)

Here is how it looks right now:
- Favorites view is good (vertically centered)
- but the all apps view is all the way to the top which looks unbalanced and makes the top apps difficult to reach

![light launcher current](https://user-images.githubusercontent.com/925062/49416286-c7345800-f779-11e8-8ac4-5f2455226afa.png)


**Here’s how it was before and should be:**
- Favorites view vertically centered (as it is now too, correctly)
- **All apps view takes the same padding value as the favorites view for top and bottom for uniform look**

![light launcher design](https://user-images.githubusercontent.com/925062/49416287-c7345800-f779-11e8-9996-8027a0e27ea0.png)



----------------


About issue number 3, I opened up a pull request at #26 and an issue at #27 :)

**Comment by postapczuk** [comment]
Ok I misunderstood you. Thought you are talking about horizontal position.

**Comment by postapczuk** [comment]
fixed
